[tool.poetry]
name = "anaconda-client-locked"
version = "1.6.14"

[tool.senv.dependencies]
python = "3.6"
anaconda-client = "1.6.14"

[tool.senv.scripts]
anaconda = "binstar_client.scripts.cli:main"

