name: CI

on: [ push ]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: [ 3.7 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: ${{ matrix.python-version }}
          activate-environment: "test"

      - name: Install senv
        shell: bash -l {0}
        run: pip install senv

      - name: Install Dependencies
        shell: bash -l {0}
        run: senv venv sync

      - name: Code Quality
        shell: bash -l {0}
        run: python black . --check

      - name: Test with pytest
        shell: bash -l {0}
        run: pytest senv --junit-xml pytest.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: pytest.xml

      - name: Publish to pypi
        shell: bash -l {0}
        if: startsWith(github.ref, 'refs/tags/')
        run:
          senv package publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --build

