name: Build and Deploy to Netlify
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - uses: Gr1N/setup-poetry@v4
      - name: Build MkDocs
        run: python3.7 -m mkdocs gh-deploy
