name: senvx-publish
on:
  push:
    tags:
      - '*'

jobs:
  build_senvx:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-64
          - os: macos-latest
            platform: osx-64
          - os: windows-latest
            platform: win-64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: 3.7
          activate-environment: "test"
      - name: install senv
        shell: bash -l {0}
        run: |
          pip install senv
      - name: install senvx virtual env
        shell: bash -l {0}
        run: |
          cd senvx
          # remove
          senv venv install

      - name: create installer
        shell: bash -l {0}
        run: |
          cd senvx
          # eval "$(conda shell.bash hook)"
          conda activate senvx
          which python
          pyinstaller main.py  -F -n senvx-${{ matrix.platform }} -c

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: senvx/dist/senvx*
          asset_name: senvx-${{ matrix.platform }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

